# Generated by Django 6.0.1 on 2026-01-19 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QWE',
        ),
    ]
