# Generated by Django 6.0.1 on 2026-01-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_delete_qwe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
